#!/usr/bin/env bash
#
# Puts the API docs generated by Typedoc into the README

cd "$(dirname "$0")"
sed -i '/<!-- API -->/,/<!-- ENDAPI -->/{/<!-- API -->/!{/<!-- ENDAPI -->/!d;};}' ../README.md
awk '/<!-- API -->/{print;system("tail -n+5 typedoc/README.md");next} 1' ../README.md > tmp && mv tmp ../README.md
