#!/usr/bin/env bash
#
# Puts the API docs generated by Typedoc into the README

cd "$(dirname "$0")"
awk '/<!-- API -->/{print;system("tail -n+7 typedoc/README.md");next} 1' ../README.md > tmp && mv tmp ../README.md
