import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, renderHook, waitFor } from '@testing-library/react';
import { getConfig } from '@openmrs/esm-config';
import { useOpenmrsPagination } from './useOpenmrsPagination';
import { useOpenmrsFetchAll } from './useOpenmrsFetchAll';

// Exercise the source implementation rather than workspace build output or a fetcher mock.
vi.mock('@openmrs/esm-api', () => import('../../esm-api/src/openmrs-fetch'));
vi.mock('@openmrs/esm-config', () => import('@openmrs/esm-config/mock'));

const mockFetch = vi.fn<typeof fetch>();

beforeEach(() => {
  window.openmrsBase = '/openmrs/';
  vi.stubGlobal('location', new URL('https://frontend.example/openmrs/spa/'));
  vi.stubGlobal('fetch', mockFetch);
  vi.mocked(getConfig).mockResolvedValue({
    redirectAuthFailure: { enabled: false, url: '', errors: [401], resolvePromise: false },
    followRedirects: true,
  });
  mockFetch.mockImplementation(async (url) => {
    const startIndex = new URL(String(url), window.location.href).searchParams.get('startIndex');
    return new Response(
      JSON.stringify({
        results: startIndex === '1' ? ['second'] : ['first'],
        totalCount: 2,
        links:
          startIndex === '1'
            ? []
            : [{ rel: 'next', uri: 'https://backend.example/openmrs/ws/rest/v1/patient?limit=1&startIndex=1' }],
      }),
      { headers: { 'Content-Type': 'application/json' } },
    );
  });
});

afterEach(() => vi.unstubAllGlobals());

it('suppresses authentication challenges on absolute URLs generated by the pagination hook', async () => {
  const { result } = renderHook(() =>
    useOpenmrsPagination<string>('/ws/rest/v1/patient', 1, {
      swrConfig: { provider: () => new Map() },
    }),
  );
  await waitFor(() => expect(result.current.data).toEqual(['first']));
  act(() => result.current.goToNext());
  await waitFor(() => expect(result.current.data).toEqual(['second']));

  expect(mockFetch).toHaveBeenCalledTimes(2);
  for (const [url, init] of mockFetch.mock.calls) {
    expect(String(url)).toMatch(/^https:\/\/frontend.example\/openmrs\/\/ws\/rest\/v1\/patient\?/);
    expect(new Headers(init?.headers).get('Disable-WWW-Authenticate')).toBe('true');
  }
});

it('suppresses authentication challenges on normalized next-page links followed by fetch-all', async () => {
  const { result } = renderHook(() =>
    useOpenmrsFetchAll<string>('/ws/rest/v1/patient?limit=1', {
      swrInfiniteConfig: { provider: () => new Map() },
    }),
  );
  await waitFor(() => expect(result.current.data).toEqual(['first', 'second']));

  expect(mockFetch.mock.calls.map(([url]) => url)).toContain(
    'https://frontend.example/openmrs/ws/rest/v1/patient?limit=1&startIndex=1',
  );
  for (const [, init] of mockFetch.mock.calls) {
    expect(new Headers(init?.headers).get('Disable-WWW-Authenticate')).toBe('true');
  }
});
