import { addSvg } from '../svg-utils';
import appointments from './svgs/Appointments-2.svg';
import appointmentsAlt from './svgs/appointments.svg';
import assessment1 from './svgs/assessment-1.svg';
import assessment2 from './svgs/assessment-2.svg';
import bloodBank from './svgs/blood-bank.svg';
import cardiology from './svgs/cardiology.svg';
import ctScan from './svgs/ct-scan.svg';
import dentistry from './svgs/dentistry.svg';
import emergencyDepartment from './svgs/emergency-department.svg';
import facility from './svgs/facility.svg';
import home from './svgs/Facility-2.svg';
import geriatrics from './svgs/geriatrics.svg';
import gynaecology from './svgs/gynaecology.svg';
import inPatient from './svgs/in-patient.svg';
import stockManagement from './svgs/inventory.svg';
import laboratory from './svgs/Labs.svg';
import labs2 from './svgs/labs-2.svg';
import obstetrics from './svgs/obstetrics.svg';
import patientLists from './svgs/Patient Management_Patients.svg';
import patientSearch from './svgs/patient-search.svg';
import patients from './svgs/patients.svg';
import paymentsDesk from './svgs/payments-desk.svg';
import pharmacy from './svgs/pharmacy-1.svg';
import pharmacy2 from './svgs/pharmacy-2.svg';
import patientRegistration from './svgs/registration.svg';
import serviceQueues from './svgs/service-queues.svg';
import transfer from './svgs/transfer.svg';
import triage from './svgs/Triage.svg';
import xray from './svgs/X-ray.svg';

export function setupPictograms() {
  addSvg('omrs-pict-appointments', appointments);
  addSvg('omrs-pict-appointments-alt', appointmentsAlt);
  addSvg('omrs-pict-assessment-1', assessment1);
  addSvg('omrs-pict-assessment-2', assessment2);
  addSvg('omrs-pict-blood-bank', bloodBank);
  addSvg('omrs-pict-cardiology', cardiology);
  addSvg('omrs-pict-ct-scan', ctScan);
  addSvg('omrs-pict-dentistry', dentistry);
  addSvg('omrs-pict-emergency-department', emergencyDepartment);
  addSvg('omrs-pict-facility', facility);
  addSvg('omrs-pict-geriatrics', geriatrics);
  addSvg('omrs-pict-gynaecology', gynaecology);
  addSvg('omrs-pict-home', home);
  addSvg('omrs-pict-in-patient', inPatient);
  addSvg('omrs-pict-laboratory', laboratory);
  addSvg('omrs-pict-labs-2', labs2);
  addSvg('omrs-pict-obstetrics', obstetrics);
  addSvg('omrs-pict-patient-lists', patientLists);
  addSvg('omrs-pict-patient-search', patientSearch);
  addSvg('omrs-pict-patients', patients);
  addSvg('omrs-pict-payments-desk', paymentsDesk);
  addSvg('omrs-pict-pharmacy', pharmacy);
  addSvg('omrs-pict-pharmacy-2', pharmacy2);
  addSvg('omrs-pict-registration', patientRegistration);
  addSvg('omrs-pict-service-queues', serviceQueues);
  addSvg('omrs-pict-stock-management', stockManagement);
  addSvg('omrs-pict-transfer', transfer);
  addSvg('omrs-pict-triage', triage);
  addSvg('omrs-pict-x-ray', xray);
}
