import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import type { TransposedValidator } from './types';

/** Everything needed to write a module's `./config-validators` entry point. */
export interface GenerateValidatorsOptions {
  /** Where to write the file. Must match the path the bundler config exposes. */
  outputPath: string;
  /** The module's hand-written validators file, if it has one. */
  authoredValidatorsFile?: string;
  /** Validators written inline in a schema, to be written out here as named exports. */
  transposed: Array<TransposedValidator>;
}

/**
 * Builds the source of the module's `./config-validators` entry point.
 *
 * The framework loads custom config validators from here by name, so that running one costs this
 * entry point's own chunk rather than the module it belongs to. Two things end up here: whatever
 * the module exports from `src/config-validators.ts`, and any validator it wrote inline in a
 * schema, whose arguments are written out as an ordinary `validator(...)` call for the bundler to
 * compile.
 *
 * Produces a module even when there is nothing to put in it: Module Federation's `exposes` are
 * fixed before the build starts, so the target has to exist regardless of what extraction finds.
 */
export function buildValidatorsModule(options: GenerateValidatorsOptions): string {
  const lines: Array<string> = [
    '// Generated by @openmrs/config-schema-plugin. Do not edit.',
    '//',
    "// This is the module's `./config-validators` entry point: the framework loads custom config",
    '// validators from here by name.',
    '',
  ];

  if (options.authoredValidatorsFile) {
    lines.push(`export * from ${JSON.stringify(options.authoredValidatorsFile)};`, '');
  }

  if (options.transposed.length > 0) {
    lines.push(
      "import { validator } from '@openmrs/esm-framework';",
      '',
      '// Written inline in a schema, where they had no name to be referred to by. Copied here so',
      '// that loading one does not mean loading the module it was written in.',
    );

    for (const entry of options.transposed) {
      lines.push(`export const ${entry.name} = validator(${entry.validationFunction}, ${entry.message});`);
    }

    lines.push('');
  }

  if (!options.authoredValidatorsFile && options.transposed.length === 0) {
    lines.push('// This module declares no custom config validators.', 'export {};', '');
  }

  return lines.join('\n');
}

/** Writes the module, leaving the file untouched when its contents have not changed. */
export function writeValidatorsModule(options: GenerateValidatorsOptions): void {
  const contents = buildValidatorsModule(options);

  let existing: string | undefined;

  try {
    existing = readFileSync(options.outputPath, 'utf8');
  } catch {
    existing = undefined;
  }

  // Rewriting an identical file would invalidate the bundler's cache and, in watch mode, start
  // another build.
  if (existing === contents) {
    return;
  }

  mkdirSync(dirname(options.outputPath), { recursive: true });
  writeFileSync(options.outputPath, contents, 'utf8');
}
