name: Report bundle size

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🚀 Setup a local cache server for Turborepo
        uses: rharkor/caching-for-turbo@2238fae6eb9a9936f92356f54cb3660200d105e7 # v2.5.1

      - name: 📊 Compute bundle size report
        uses: preactjs/compressed-size-action@261e5e2bb5332e35c78914ce69b4edcdf30da2ed # v3 branch
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          minimum-change-threshold: 10000 # 10 KB
          install-script: "yarn install --immutable"
          build-script: "yarn turbo run build --color"
          clean-script: "yarn run clean:dist"
