name: OpenMRS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release version bump'
        type: choice
        options: [patch, minor, major]
        default: patch
      custom_version:
        description: 'Custom version (e.g. 12.5.0). If set, overrides the version bump above.'
        required: false
      publish_only:
        description: 'Re-Publish only (For recovering from a failed npm publish. Skips the version bump, commit, and tag. Set "Custom version" to the existing release version, e.g. 12.4.0.)'
        type: boolean
        default: false
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/build-frontend-module.yml@main
    with:
      enable_turborepo_cache: true
      verify_command: 'yarn verify --concurrency=5'

  release:
    needs: build
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/release-frontend-module.yml@main
    with:
      enable_turborepo_cache: true
      pre_release_version_command: 'yarn workspaces foreach --worktree --topological --exclude @openmrs/esm-core version "$PRERELEASE_VERSION"'
      pre_release_publish_command: 'yarn run ci:publish-next'
      release_publish_command: 'yarn run ci:publish'
      release_type: ${{ inputs.release_type }}
      release_version: ${{ inputs.custom_version }}
      publish_only: ${{inputs.publish_only}}
      artifact_path: 'packages/**/dist'
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      BOT_PAT: ${{ secrets.OMRS_BOT_GH_TOKEN }}
