name: OWASP Dependency Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: {} # No direct permissions needed, the reusable workflow manages its own

jobs:
  build:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/owasp-dependency-check.yml@main
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      BOT_GH_TOKEN: ${{ secrets.OMRS_BOT_GH_TOKEN }}
