name: PR title check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  pr-title:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/frontend-pr-title-check.yml@main
    with:
      pr-title: ${{ github.event.pull_request.title }}
      pr-author-login: ${{ github.event.pull_request.user.login }}
      pr-author-type: ${{ github.event.pull_request.user.type }}
