name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: 'docs, fix, feat, BREAKING'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
