name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Version bump'
        type: choice
        options: [patch, minor, major]
        default: patch
      custom_version:
        description: 'Custom version (e.g. 12.5.0). If set, overrides the version bump above.'
        required: false
      publish_only:
        description: 'Re-Publish only (For recovering from a failed npm publish. Skips the version bump, commit, and tag. Set "Custom version" to the existing release version, e.g. 12.4.0.)'
        type: boolean
        default: false
        required: false
jobs:
  release:
    permissions:
      contents: write
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/release-frontend-module.yml@frontend-tagged-release
    with:
      release_type: ${{ inputs.release_type }}
      release_version: ${{ inputs.custom_version }}
      publish_only: ${{inputs.publish_only}}
      release_publish_command: 'yarn pack'   # stands in for npm publish
    secrets:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      BOT_PAT: ${{ secrets.OMRS_BOT_GH_TOKEN }}
